uploads = []

[[generated]]
id = "lWNqC1uqRKaLXvC58jJWw"
uri = "file://client/src/assets/shield-glass.png"
type = "image"
title = "bold-wide-glass-shield"

[[outputs]]
id = "ICpmWszxOSiaHnLLCMBIa"
uri = "file://client/src/assets/shield-glass.png"
type = "image"
title = "New Glass Shield"
