uploads = []

[[generated]]
id = "lWNqC1uqRKaLXvC58jJWw"
uri = "file://client/src/assets/shield-glass.png"
type = "image"
title = "frosted-glass-heraldic-shield-correct-shape"

[[outputs]]
id = "ICpmWszxOSiaHnLLCMBIa"
uri = "file://client/src/assets/shield-glass.png"
type = "image"
title = "Isolated Frosted Glass Shield"
